all:
  children:
    ad:
      hosts:
        srv-ad-01:
          ansible_host: 192.168.1.60
          ansible_connection: winrm
          ansible_user: Administrateur
          ansible_password: "{{ vault_windows_admin_password }}"
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_scheme: http
          ansible_winrm_server_cert_validation: ignore

    nextcloud:
      hosts:
        srv-nextcloud-01:
          ansible_host: 192.168.1.50
          ansible_user: nicolas
